version: '2'
services:
  mutexparamsadmin-app:
    image: mutexparamsadmin
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mutexparamsadmin-mysql:3306/mutexparamsadmin?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8100:8100
  mutexparamsadmin-mysql:
    extends:
      file: mysql.yml
      service: mutexparamsadmin-mysql
